{
 "title": "FastAPI Observability",
 "tags": [
  "fastapi",
  "observability",
  "backend",
  "overall"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name" },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"}[24h]))"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_request_duration_seconds_sum{handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"}[5m])) / sum by(handler, method) (rate(http_request_duration_seconds_count{handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"}[5m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status=~\"5..\", handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"}[24h])) or vector(0)"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{status=~\"2..\", handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"}) / sum by(handler) (http_requests_total{handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(handler) (http_requests_total{status=~\"5..\", handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"}) / sum by(handler) (http_requests_total{handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"})) or vector(0)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"}[5m])) by (handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "http_requests_in_progress{handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"} or vector(0)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler, method, status) (rate(http_requests_total{handler!=\"/metrics\",handler!=\"/docs\",handler!=\"/openapi.json\",handler!=\"/redoc\",handler=~\".+\"}[1m]))",
     "legendFormat": "{{method}} {{handler}} ({{status}})"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({container=~\"fastapi-project.*\"} |~ `(?P<level>INFO|ERROR|WARNING|CRITICAL|DEBUG)` |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Log of All FastAPI App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "{container=~\"fastapi-project.*\"} |= \"$log_keyword\""
    }
   ]
  }
 ]
}